// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpkDKq1nIepLT4zVrUkXcdxAq7WTu0_o',
    appId: '1:549603731179:android:fc8a3e3f97c3c3a6fa80ae',
    messagingSenderId: '549603731179',
    projectId: 'pucket-f958c',
    authDomain: 'pucket-f958c.firebaseapp.com',
    storageBucket: 'pucket-f958c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpkDKq1nIepLT4zVrUkXcdxAq7WTu0_o',
    appId: '1:549603731179:android:fc8a3e3f97c3c3a6fa80ae',
    messagingSenderId: '549603731179',
    projectId: 'pucket-f958c',
    storageBucket: 'pucket-f958c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswReh7Hu0lfJMt8FWGoF7-Z2KPug_Cpg',
    appId: '1:549603731179:ios:20c0513cf9f9aba8fa80ae',
    messagingSenderId: '549603731179',
    projectId: 'pucket-f958c',
    storageBucket: 'pucket-f958c.firebasestorage.app',
    iosClientId: '549603731179-tl87pvasv9jsf2gehl7phref0s2cb44k.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswReh7Hu0lfJMt8FWGoF7-Z2KPug_Cpg',
    appId: '1:549603731179:ios:20c0513cf9f9aba8fa80ae',
    messagingSenderId: '549603731179',
    projectId: 'pucket-f958c',
    storageBucket: 'pucket-f958c.firebasestorage.app',
    iosClientId: '549603731179-tl87pvasv9jsf2gehl7phref0s2cb44k.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
}
