// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy114yEHnrXeZ5rQrQ1uCALFGJEk_z-Yo',
    appId: '1:834928081370:web:c5029e9b0f9c4cedf268e3',
    messagingSenderId: '834928081370',
    projectId: 'pucket-202607',
    authDomain: 'pucket-202607.firebaseapp.com',
    storageBucket: 'pucket-202607.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWg-m_KT59ubc5nHT0ovVOu2R897JF-E',
    appId: '1:834928081370:android:89b888b55f744e4af268e3',
    messagingSenderId: '834928081370',
    projectId: 'pucket-202607',
    storageBucket: 'pucket-202607.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAIV2Ub_puscY3Ea1nRv5UGthI_uPyEgw',
    appId: '1:834928081370:ios:e8ede0dab3b63da0f268e3',
    messagingSenderId: '834928081370',
    projectId: 'pucket-202607',
    storageBucket: 'pucket-202607.firebasestorage.app',
    iosClientId: '834928081370-8joaucc5tjldsrd7e080ck7sufh0d6so.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAIV2Ub_puscY3Ea1nRv5UGthI_uPyEgw',
    appId: '1:834928081370:ios:e8ede0dab3b63da0f268e3',
    messagingSenderId: '834928081370',
    projectId: 'pucket-202607',
    storageBucket: 'pucket-202607.firebasestorage.app',
    iosClientId: '834928081370-8joaucc5tjldsrd7e080ck7sufh0d6so.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
}
