// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjf28PLC1LJyxy6kd3Jy8bOIYCEmpmjw',
    appId: '1:461164328612:android:f3bec96b611ca30b311831',
    messagingSenderId: '461164328612',
    projectId: 'pucketyeni',
    authDomain: 'pucketyeni.firebaseapp.com',
    storageBucket: 'pucketyeni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjf28PLC1LJyxy6kd3Jy8bOIYCEmpmjw',
    appId: '1:461164328612:android:f3bec96b611ca30b311831',
    messagingSenderId: '461164328612',
    projectId: 'pucketyeni',
    storageBucket: 'pucketyeni.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYymolaAzDtpY4_FvF7-bP_Uh6VZfDjI',
    appId: '1:461164328612:ios:bf4d5d789d82082a311831',
    messagingSenderId: '461164328612',
    projectId: 'pucketyeni',
    storageBucket: 'pucketyeni.firebasestorage.app',
    iosClientId: '461164328612-fbt9ckaiab0diimgkm4ii0rohs77ihf2.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQYymolaAzDtpY4_FvF7-bP_Uh6VZfDjI',
    appId: '1:461164328612:ios:bf4d5d789d82082a311831',
    messagingSenderId: '461164328612',
    projectId: 'pucketyeni',
    storageBucket: 'pucketyeni.firebasestorage.app',
    iosClientId: '461164328612-fbt9ckaiab0diimgkm4ii0rohs77ihf2.apps.googleusercontent.com',
    iosBundleId: 'com.pucket.pucketFlutter',
  );
}
