#!/usr/bin/env bash
# Apple Sign-In — Xcode + Firebase + Apple Developer kontrol listesi
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUNDLE_ID="com.pucket.pucketFlutter"

echo "=== PUCKET Apple Sign-In kurulumu ==="
echo ""
echo "Kod tarafı hazır:"
echo "  • ios/Runner/Runner.entitlements → com.apple.developer.applesignin"
echo "  • ios/Runner/RunnerDebug.entitlements → com.apple.developer.applesignin"
echo "  • Info.plist → NSAppleSignInUsageDescription"
echo ""
echo "Senin yapman gerekenler (sırayla):"
echo ""
echo "1) Xcode"
echo "   open $ROOT/ios/Runner.xcworkspace"
echo "   Runner → Signing & Capabilities"
echo "   • Team: Apple Developer hesabını seç"
echo "   • Bundle ID: $BUNDLE_ID"
echo "   • + Capability → Sign in with Apple (zaten entitlements’ta var, doğrula)"
echo ""
echo "2) Apple Developer (developer.apple.com)"
echo "   Certificates, Identifiers & Profiles → Identifiers"
echo "   • App ID: $BUNDLE_ID"
echo "   • Sign in with Apple → Enable → Save"
echo ""
echo "3) Firebase Console (pucket-202607)"
echo "   Authentication → Sign-in method → Apple → Enable → Save"
echo "   (Services ID gerekmez — yalnızca native iOS için)"
echo ""
echo "4) Simülatör testi"
echo "   Simülatör → Settings → Apple Account → Apple ID ile giriş yap"
echo "   Sonra: flutter run -d <simulator>"
echo ""
echo "5) Gerçek cihaz (önerilen)"
echo "   iPhone’a bağla, Xcode Team seçili olsun, flutter run"
